#![allow(clippy::single_char_add_str)]

include!("build/gen.rs");

fn main() {
    println!("cargo:rerun-if-changed=build/stdlib.md");
    println!("cargo:rerun-if-changed=build/language.md");
    println!("cargo:rerun-if-changed=build/config_variables.md");
    // println!("cargo:rerun-if-changed=src/gen/");

    let mut text = r#"
// This file is auto-generated by build.rs do not edit
use json::object;
    "#
    .to_string();

    let probes_md = fs::read_to_string("build/language.md").expect("Read failed");
    let stdlib_md = fs::read_to_string("build/stdlib.md").expect("Read failed");
    let conf_vars_md = fs::read_to_string("build/config_variables.md").expect("Read failed");

    text.push_str(&gen_completion_probes(&probes_md));
    text.push_str(&gen_completion_stdlib(&stdlib_md));
    text.push_str(&gen_completion_config_variables(&conf_vars_md));

    fs::write("src/gen/completion.rs", text).expect("Write failed");
}
