[package]
name = "bpftrace-ls"
version = "0.1.0"
edition = "2021"

[features]
parser_diagnostics = []
live_btf_tests = []
debug_command = []

[dependencies]
json = "0.12.4"
tree-sitter = "0.27"
tree-sitter-bpftrace = "0.4.1"
binrw = "0.15"
enum_dispatch = "0.3"
memmap2 = "0.9.10"
xflags = "0.3.2"
glob-match = "0.2.1"
libc = "0.2.189"
